### ISSUE TITLE
Add ability to lock some weapons to a specific character

### ISSUE THREAD

**Issue by AndreyMikhailov** [dasilva333/TowerGhostForDestiny#100]
Please add an ability to lock some weapons to a specific character. For example I have 3 icebreakers on each character and I don't want them been moved when I equip any loadout.

**Comment by pattont** [comment]
Yea, cool idea. I was thinking the logic could be smarter than just locking it to a character. Basically, if you have 3 Icebreakers and you have one in a loadout you want to use. If you are moving that loadout to another character and an icebreaker already exists then don't move it and if you selected to equip it then equip the found duplicate. 

Instead of having to go and "lock" to a certain character, you are just preventing a duplicate from being transferred which I am sure that everyone will be ok with. No one needs 2x Icebreakers on the same character :-)

**Comment by AndreyMikhailov** [comment]
There is also already a feature that moves some weapons to the vault if there is not enough space in the character's slot. So basically such "locked" weapons should not be moved in this case and other "not locked" weapons must be moved. :-)

**Comment by dasilva333** [comment]
Yeah I agree I always wanted to find a way to improve the swap tech since the finding a random weapon in the bucket isn't always the best option. I've considered allowing the user to change the weapon it decided to swap with but that would involve even more UI issues. So perhaps this is the best way. I'll mark this as an enhancement and leave it for long term. Thanks for your feedback guys

**Comment by AndreyMikhailov** [comment]
dasilva333, thank you for your awesome work!

**Comment by dasilva333** [comment]
This has been fixed as of 2.9.3 @AndreyMikhailov FYI the logic is seamless it doesn't require user interaction I simply added another layer of logic where it first excludes items of the same kind in both buckets, before it then continues to filter by items of the same type, and reverts to any item if it can't find a match. Let me know how it goes for you now thanks.
