### ISSUE TITLE
WP: 2.1.7 constant blue loading bar

### ISSUE THREAD

**Issue by equesaspe** [dasilva333/TowerGhostForDestiny#104]
After logging in there is a constant blue loading bar. No items load. Lumia 1520.

**Comment by pattont** [comment]
Have you tried to force close and come back in. I've had that issue before on the iOS beta.

**Comment by equesaspe** [comment]
Still no go. Similar to earlier issue. I am going to test it on my Lumia 1520 running WP 10 to see if I can duplicate.

**Comment by equesaspe** [comment]
No G on both devices.

**Comment by dasilva333** [comment]
Sometimes the updater messes it up and you have to do a full uninstall and reinstall to get it to work again, the updater blue bar used to be short before I introduced local image caching and sometimes it takes really long. This problem is especially apparent on windows phones. @equesaspe try uninstall and let me know thanks

**Comment by equesaspe** [comment]
That worked. Thanks.
