### ISSUE TITLE
iOS Slowdown

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#161]
The most recent few versions seems extremely slow to load especially once a new version is loaded. Ultimately, when the app is loaded and all of my inventory appears everything is fine, but when I am waiting for it to load it's taking much longer than some of the older versions. 

Killing the app and re-loading does not help. 

This is the screen I sit on ALOT on both my iPad Mini 2 and iPhone 6 and it seems never ending. 
![image](https://cloud.githubusercontent.com/assets/2903357/7557755/522440b0-f765-11e4-9959-af331ec6f69d.jpg)

**Comment by M3Rocket** [comment]
This also happens on Android with the latest versions. 

I can reproduce it eaily--delete the cache and program data, let the program update via hydrate. Then on first load, sign-in via PSN. The "Loading user data..." bar appears, then disappears. Wait about 20-25 seconds and everything is there although some icons might be broken. 

After the initial load, hit "Refresh", now the "Loading user data..." bar stays on screen. After about 7-10 seconds, the vault appears. From there, it takes anywhere from 50 seconds to 70 seconds for the rest of the inventory to appear. Sometimes, it just hangs and nothing else ever loads.

I can prevent this by deleting cache and data, restart Tower Ghost for Android, selec "Ignore for now" when the new hydrated version shows up. Of course, then I'm using version 2.1.4 instead of the latest 2.4.x

**Comment by dasilva333** [comment]
On iOS the system can't remember your authenticated cookies so it has to re-authenticate the cookie every time you open the app, that's why prior to 2.2.8 there was always a sign in screen. After that version the sign in prompt was merely replaced with an automated way of signing in by opening a hidden window for Bungie.net and waiting for their servers to authorize you. That's why the process "Please wait, your inventory is loading" can take anywhere between 1 second and 2 minutes it's completely up to Bungie during that phase. 

For Android it's a completely different story the cookies are always there so users just have to deal with one "Loading user data" bar which depends on how fast your connection/device is at loading the actual data. I've profiled the loading time it takes between 'loading user data' and when everything is done loading and on average it takes about 10 seconds on my iPhone 5 and 40 seconds on my windows phone

Thanks for your feedback guys, basically there's stuff during the loading process I can't fix like the extra step ios/windows-phone has to take to re authenticate the cookie and there's stuff I can look at again to make sure it's working right. I'll revisit the loading times during 'loading user data' to make sure its still around 10 seconds for my phone and if it is I'll go ahead and close this ticket.

Thanks again

**Comment by matthubb** [comment]
I'm not sure they are just referring to the initial start up time: I was using it on an iPad 3 (or maybe 2) last Wednesday and inventory refreshes were taking so long I'd think it had crashed.

**Comment by pattont** [comment]
Yea, even before when I had to click the sign-in on Bungie.com through iOS
it wasn't as slow as it is now. There were times when the old login
wouldn't go away after the page was loaded, but the app would work even
when manually closing it.

I'm guessing you have an async function to fetch the cookie and when it's
received kicks off the inventory load?

**Comment by M3Rocket** [comment]
Should I open another issue for the Android delayed/slow inventory loading problem? The delay between 2.1.4 and 2.4.8 is quite noticeable.

**Comment by dasilva333** [comment]
@M3Rocket no don't open another issue if anything I'll rename the title for this issue

@pattont The cookie is fetched really quickly within the first second of loading the app, that cookie is always bad for ios/wp so it has to get a new one from bungie that process takes 1 second to 1 minute
on android that same cookie is always good so it skips straight to the loading process

The actual loading process is the time between 'loading user data' and when everything has finished loading on the screen, as I said earlier I'll benchmark my phone again and make sure that time is still within 10 seconds if it's not then it's a problem and I'll leave this ticket open, 

Thanks again guys

**Comment by dasilva333** [comment]
Thanks @pattont I bug found, introduced by the simple 'duplicates filter' not only was it increasing my loading time by 3x what it should be but it was also doubling the time it took to refresh every time so 10s, 20s, 30s, 45s for every refresh.

Thanks again expect the fix in 2.4.9

**Comment by pattont** [comment]
Excellent news :-)

**Comment by matthubb** [comment]
This appears to have resolved the slowdown for me. Thank you.

**Comment by M3Rocket** [comment]
Confirmed fixed for me as well on Android.
