### ISSUE TITLE
issue on kindle fire hd

### ISSUE THREAD

**Issue by MercenaryDF** [dasilva333/TowerGhostForDestiny#175]
I was enjoying optimal functionality  for well over a week then on thursday may 7th i couldn't load up. It was stuck in the loading screen. I tryed again a few minutes later and it was the same. So i uninstalled and reinstalled it. This time i got stuck at the Bungie.net page with it already recognizing my account. When i x out it always prompts me to sign in. When i try it recognizes my bungie.net account. I can't recall the version i was running but i have been downloading each update never skipping.

**Comment by dasilva333** [comment]
Try this version it's 2.3.7 before I implemented the auto sign in:
https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestiny-issue-175.ipa?raw=true

To install it there's two methods:
1. if you're jailbroken you should be able to just install it using your normal method (ifunbox etc)
2. if you're not broken you need to provide me your UDID (http://whatsmyudid.com/) and email so that when you try to install that file via iTunes it'll work for you.

Thanks

**Comment by MercenaryDF** [comment]
That worked perfectly your the man !! Thanks for your help !!

**Comment by dasilva333** [comment]
I'm glad i got an interim solution for you but the real fix would be making it work in the current version with whatever I changed. Stay tuned while I provide you a debug build to figure out what's wrong. Thanks

**Comment by dasilva333** [comment]
@MercenaryDF closing this ticket, please try version 2.9.1 and above and let me know if you're still having any issues. thanks
