### ISSUE TITLE
Weapon detail not working properly on iPhone 

### ISSUE THREAD

**Issue by revdarwin** [dasilva333/TowerGhostForDestiny#176]
![image](https://cloud.githubusercontent.com/assets/12428509/7610053/33d5e0ec-f93f-11e4-81d4-a9ca0c001a84.jpg)

I get this when I long press a weapon in the iPhone 6 iOS 8.3.

**Comment by dasilva333** [comment]
Does it happen sometime or everyti me? Can anyone else reproduce this? Let me know Thx

**Comment by matthubb** [comment]
No problem on TestFlight TGD version 2.5.4 on iPhone 6.

**Comment by revdarwin** [comment]
Doesn't happen every time. Sometimes it doesn't pull up anything at all. Then sometimes I can only see a small corner of it. 

Seems like most of the time I get the detail as long as I keep my finger down but it disappears when I release to move my finger out of the way to read it.

**Comment by dasilva333** [comment]
Switching from bug to enhancement since it only occurs during certain situations, it might be due to a network error or a connection aborted. I'm using a third party plugin so I'm not sure if I can fix the problems within it. The way it's supposed to work is as follows:

1. Hold finger on item wait until it says Loading... (release finger) pop up should open and stay open because the finger was released before it finished loading
2. Hold finger on item wait until it says Loading, wait until it finished loading (release finger) pop up should disappear and only remain open while your finger is holding it in place. 

The idea is option one lets you toggle it on/off, and the second option let's you get a quick view without having to tap it again to dismiss, if you have trouble reading the text while holding you can move your finger elsewhere in the popup and it'll still stay open or release your finger before it finishes loading.
