### ISSUE TITLE
New 2.5.7 redesigned weapon attack values font size too large and/or icons too small

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#187]
@bluetidepro Overall, very nice design refresh! Thank You!

The attack values text overlay on the reduced size weapon icons are too large resulting in most of the icons being obscured. 

Nexus 4 (4.7" screen):
![nexus4_2015-05-14-18-39-49](https://cloud.githubusercontent.com/assets/3769123/7645437/10d72f8e-fa6a-11e4-8ee2-308e0cdef309.png)
![nexus4_2015-05-14-18-40-02](https://cloud.githubusercontent.com/assets/3769123/7645440/174c28c4-fa6a-11e4-9e6d-e7048cd505ad.png)

Nexus 7 (7" screen):
![nexus7_2015-05-14-18-17-39](https://cloud.githubusercontent.com/assets/3769123/7645494/b2f0d838-fa6a-11e4-91d2-a488c1d4d9f0.png)
![nexus7_2015-05-14-18-17-45](https://cloud.githubusercontent.com/assets/3769123/7645492/aed35578-fa6a-11e4-98be-748ff9401937.png)

Nexus 4 with old design:
![screenshot_2015-05-03-11-33-35](https://cloud.githubusercontent.com/assets/3769123/7645552/9879ce28-fa6b-11e4-88fd-9f10dfae229d.png)

Some more observations:

1. From a utility standpoint, seems like perhaps a little bit too much white space between the columns. 

2. I don't like the reduction in icon size with an increased icon border size. The old sizes seem to work better for my fat fingers on mobile especially. Currently, it is unusable on the Nexus 4 in portrait mode in 2-columns mode.

3. The attack values are mostly the same with all my weapons anyway, and it clutters up the screen when it visually takes up so much space relative to the graphic/icon. I wonder if the attack values should be an overlay that appears only when you hover over an icon? Or actually have a toggle on the menu to turn the overlay into a colored elemental indicator?

**Comment by bluetidepro** [comment]
@M3Rocket Good notes, I'll look at all these issues and see what I can do :)

**Comment by Doubleken** [comment]
I got the same problem too, Damage Font is too large, and Icon is too small
![screenshot_2015-05-15-10-29-04](https://cloud.githubusercontent.com/assets/12265051/7645827/89a1f434-faed-11e4-911f-667d066fd84f.jpeg)
and "Equipped" text is too long, that only show 1 column now :( (before can show two)
![screenshot_2015-05-15-10-29-19](https://cloud.githubusercontent.com/assets/12265051/7645844/c960f12e-faed-11e4-81c9-905051b87dc1.jpeg)

**Comment by TheNcredibleMrE** [comment]
I'm also having these issues. (galaxy note 4) The damage values are too big and the columns aren't aligning properly. I do really enjoy this app and thank you for the constant support. The UI look itself other than the bugs is great. Maybe add a size toggle for the icons because I find those too small as well.  I liked it back a few updates ago when they were about 100%-150% larger. A toggle would be great.
pics of the bugs below. Thanks again.
![screenshot_2015-05-15-18-10-04](https://cloud.githubusercontent.com/assets/12467379/7663794/971e823a-fb2e-11e4-80f6-5b8ea2ed3ff4.png)
![screenshot_2015-05-15-18-10-47](https://cloud.githubusercontent.com/assets/12467379/7663798/9d21aa90-fb2e-11e4-8f98-141c46111734.png)
![screenshot_2015-05-15-18-10-35](https://cloud.githubusercontent.com/assets/12467379/7663800/a19c58d6-fb2e-11e4-912f-707a339ee04a.png)

**Comment by ipaintformoney** [comment]
Having all of these same issues on my LG G3.

**Comment by Joshbuss** [comment]
As well as on my HTC m8
