### ISSUE TITLE
Serve and cache item definitions

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/TowerGhostForDestiny#203]
Instead of requiring a new build when Bungie updates the definitions, serve the JSON from TowerGhostForDestiniy.com and cache them in local storage.

Do a simple check on start up to see if there's a new definition file and download if required.

**Comment by joshhunt** [comment]
I've actually created a service for this: [destiny.plumbing](http://destiny.plumbing). (see source code joshhunt/destinyData). It's all stored on AWS S3 so it's highly reliable and cheap to run.

At the moment it's a straight dump of the `mobileWorldContent en` database, to a JSON object with item hashes as the key. Later on I plan on creating specific endpoints for just weapons, armour, weapons by damage type or class etc, but only when I get time (finish Prison of Elders).

Anyway - feel free to use it.

**Comment by dasilva333** [comment]
Actually I was talking to Shawn what I had in mind as the gameplan:

1. Modify my update_definitions scripts where it downloads just "en"
https://github.com/dasilva333/TowerGhostForDestiny/blob/master/build/update_definitions.js#L115
2. Download all languages available and *run it through the post processing*
3. Upload a copy to my towerghostfordestiny.com
4. Modify the app to check app.activeUser().user.locale to make sure it matches what you have cached
5. add a second check to make sure it's not outdated

The reason I wouldn't use the raw json files is because they're huge and filled with unnecessary data so I would rather leave all the post processing of the json files to be done at the server side rather than the client side.

Thanks!

**Comment by joshhunt** [comment]
Sure - The files are massive and full of  _lots_ of 'useless' data. Eventually I'll create smaller files of select data, but I couldn't give you an exact date.

Anyway, they'll always been there if anyone wants them.
