### ISSUE TITLE
Loadout changes, deletions, additions not saving

### ISSUE THREAD

**Issue by MandarbTX** [dasilva333/TowerGhostForDestiny#224]
Unable to add, save, delete or change loadouts. Each time I attempt any of these activities, the loadouts revert to what was saved a couple of days ago. This happens after refreshing in app or after restating. App does report that it saved successfully.

**Comment by MandarbTX** [comment]
This is in the Android app

**Comment by ssoriche** [comment]
Seeing the same problem with Chrome.

**Comment by Tastix** [comment]
I'm having this same issue on iOS, in Chrome on OS X, and in Firefox. Can't seem to edit or remove or make any changes to my load outs at all. 

Only recently will it not let me update or adjust any of the load outs. I have even tried deleting all of them, but when I refresh they all just come back (by refresh I mean control + r, not the in app refresh).

Since this issue popped up I have been unable to edit, change, add new ones, or remove any of the load out builds I have.

I access my account on an iPad and two computers. The issue appears on all three 3 devices. To troubleshoot I have uninstalled the IOS app and removed the tooltip from Chrome in one computer so my account is only set up on one device but no change. No errors come up, it let’s me create and edit load outs, but as soon as I refresh the screen it goes way, or if I leave and log back in later it goes away.

**Comment by M3Rocket** [comment]
This is happening with both Android and Chrome for me as well.

**Comment by dasilva333** [comment]
anyone confirm its sill a problem?

**Comment by M3Rocket** [comment]
Just checked. Seems to be fixed.

**Comment by ssoriche** [comment]
Changes I made on Chrome earlier are showing in iOS.

**Comment by MandarbTX** [comment]
Seems to be fixed for me, thanks!
