### ISSUE TITLE
destiny.plumbing is available for JSON item feeds

### ISSUE THREAD

**Issue by joshhunt** [dasilva333/TowerGhostForDestiny#241]
I've created [destiny.plumbing](http://destiny.plumbing/) which hosts up-to-date JSON feeds for all item information from Destiny, in all locales available.

There are two sets of 'feeds' available:

 * **raw:** These are straight dumps of all tables from the `mobileWorldContent`, gzipped and served. While a standard JSON dump of `DestinyInventoryItemDefinition` is around 5MB, gzipped it is only 575 KB

 * **specialised:** The DestinyInventoryItemDefinition items are then processed further and split out into specified feeds with only unnecessary data removed to reduce file size. The [english feed](http://destiny.plumbing/items/en.json) for all items is just 252 KB.

[destiny.plumbing](http://destiny.plumbing/) contains an index of all content, so it's much preferred that URLs are fetched from that first incase the JSON url format is changed.

These are updated multiple times a day to ensure the latest data is always available.

Tell me what you think and if you're interesting in using it. The code powering this is [on github](https://github.com/joshhunt/destinyPlumbing) and I'm accepting PRs.  

If you're interested, and if there are any changes you would like to see in the specialised feeds, just hit me up and I'll see what can be done.

**Comment by dasilva333** [comment]
Thanks man that's great I'm really impressed by how you got the post-processor in there for the specialised set. I've been working on a completely separate branch called content-sync

https://github.com/dasilva333/TowerGhostForDestiny/tree/content-sync

It's basically TGD + a new loader that replaces hydra, the app is broken into 3 pieces www, itemDefs and icons. ItemDefs is probably where the Content-Sync plugin I'm using would have to change to this URL: http://destiny.plumbing/items/en.json

However after analyzing it there's differences in how I encode strings:

https://raw.githubusercontent.com/dasilva333/TowerGhostForDestiny/content-sync/www/data/itemDefs.js

I'm not sure if I can overcome the encoding problem by downloading the files rather than loading them via script tags so I'll have to test it and see, if you'd like to see through the code I'm talking about you can find it here:

https://github.com/dasilva333/TowerGhostForDestiny/blob/content-sync/www/js/loader.js#L199

Thanks

**Comment by joshhunt** [comment]
Why do have you percent encoded strings in your `itemDefs.js`? In `update_definitions.js`, you're running  the string values through `encodeURIComponent `, even though you're not using them in a URI/URL.  

I don't encode my strings for URL because they're not going in URLS :)

**Comment by joshhunt** [comment]
And I'm going to do a bit of a rework of the code to make it easier to just run normally on a computer rather than on AWS Lambda (I'm abusing it and it's not really working out properly). If all you get from this is some ideas and code that you can use in your own project, I would still call that a success :)
