### ISSUE TITLE
Normalize option for material not working as expected

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#253]
When I try to consolidate materials (Helium Filaments in this case), the results are not quite what I expected. My steps are: Helium Filaments -> Extras, select each of my 3 characters (an not the Vault) and click on Normalize. When it is all said and done I end up with Helium Filaments in my Vault, and if I try it a second time it tells me the items are already normalized.

![screen shot 2015-06-15 at 10 31 39 am](https://cloud.githubusercontent.com/assets/12019978/8163759/9800a8f2-134a-11e5-9a06-1015acf29e7e.png)

![screen shot 2015-06-15 at 10 31 53 am](https://cloud.githubusercontent.com/assets/12019978/8163764/9f97901c-134a-11e5-9737-5eb7ea87624b.png)

Here is what I end up at the end of the Normalization process:
![screen shot 2015-06-15 at 10 31 13 am](https://cloud.githubusercontent.com/assets/12019978/8163775/ae703454-134a-11e5-943e-388ae24ef24c.png)

**Comment by weborican** [comment]
Looking at the total displayed (928), I have a feeling this feature doesn't work as I expected.

My expectation was that ALL Helium Filaments would be normalized across my selected characters, not normalize ONLY the Helium Filaments currently on the selected characters among themselves.

Basically, this may not be a bug... but rather a misunderstanding of the Normalize feature :-(

**Comment by dasilva333** [comment]
Yeah I'm not sure of @Mulchman's intent on this one I'll leave it up to him to decide whether it's a bug or not

**Comment by M3Rocket** [comment]
I got confused reading the title thinking it was consolidate (Issue https://github.com/dasilva333/TowerGhostForDestiny/issues/245), but seems to refer to normalize (Issue https://github.com/dasilva333/TowerGhostForDestiny/issues/122)?

I can't reproduce your first step when you said you select three characters but not the vault to normalize. If you do that and there were no helium filaments in your vault, there shouldn't be any after normalization since the vault wasn't selected. 

The second part is working as designed: Normalize from selected characters/vault to selected characters/vault. A more advanced distribute involving different origins and destinations was discussed in issue https://github.com/dasilva333/TowerGhostForDestiny/issues/122.

I'll test this more when Bungie's servers are back up. It is down right now for a maintenance patch.

**Comment by weborican** [comment]
Sorry, yes... "nomalize" is what I was referring to. In my example there were Helium Filaments in my Vault. I clicked on them (on the Vault) and selected Normalize (with my 3 characters selected, but not the Vault).

**Comment by Mulchman** [comment]
@weborican It's doing what it's supposed to: it only normalizes between the characters that are selected. Whether that's good or bad for most users, I can't say, but it's how I personally wanted it to work. (I leave things in the vault that aren't to be touched.)

I mocked up a more advanced type of normalize dialog but it was too confusing and got shot down (http://imgur.com/z9p1H6v). It let you multi-select the source characters, the target characters, the consumables/materials, and then it would transfer+normalize based on the various selection. There was some prototype/mockup discussion mentioned in the slack chat (https://towerghostfordestiny.slack.com/messages/equalize_normalize/) but I haven't tried to follow up with @bluetidepro in quite a while. I basically wanted a user configurable way to do a mass normalize of all consumables/materials (excluding the vault 'cause *don't touch my vault, bro!*) instead of having to go one by one.

**Comment by Mulchman** [comment]
and to add- @weborican to get what you want, manually move that Helium to any player, then do the normalize process. :/

**Comment by Mulchman** [comment]
and another thing I forgot- @weborican that 928 number is the sum of Helium on the selected characters. It should change as you change selection.

**Comment by Mulchman** [comment]
(and I edited the title as it confused me as well initially)

**Comment by M3Rocket** [comment]
I'm not sure this should be classified as a bug anymore. Seems to me it's working as intended and should be closed. Perhaps we should further the discussion on a more "Advanced" normalize in issue https://github.com/dasilva333/TowerGhostForDestiny/issues/122.
