### ISSUE TITLE
Logging into Bungie

### ISSUE THREAD

**Issue by SunburnedGoose** [dasilva333/TowerGhostForDestiny#340]
I was checking out your v3 updates on my phone, and noticed how long it has taken to open up the app and get to my character screens.  What's going on during this phase that takes ~two minutes to complete?  I usually have to wake up my phone to see if it completed.  The chrome extension seems to load quick enough.

**Comment by dasilva333** [comment]
@SunburnedGoose for a developer you're pretty clunky with your bug reports, please provide the version #, the phone platform and the color of the loading bar it is stuck in for you to be able to know if this is an actual issue or not.

Thanks

**Comment by SunburnedGoose** [comment]
It wasn't a bug report; I was looking for more of a conversation between
developers.

**Comment by dasilva333** [comment]
A proper conversation can only be had with all the relevant details, something you're not willing to disclose even after asking for it specifically. Let me know when you're ready to actually discuss it

**Comment by SunburnedGoose** [comment]
I'm asking for a high level overview of what your app is doing that takes
up to two minutes to complete. Your app isn't stuck, it is just slow to get
me past the open screen to my character on mobile.

If it helps, v3.0.5, iOS, and a yellow bar.

**Comment by dasilva333** [comment]
On iOS there's a problem with maintaining state vs other platforms like Android. So on iOS 6/7/8 what I do is log the user in, save the bungled key and reuse it in future sessions. The yellow bar means it's trying to validate the bungled key is working, green bar means it's past authentication and it's just at the loading phase (driven by your connection speed). The trick to maintaining state in IOS/WP is using the setRequestHeader("Cookie") for ajax requests this allows TGD to trick the code into thinking this is an existing session rather than a new one when they re open the app, if the trick fails and the cookie has already expired or is invalid the system uses a retry algorithm to automatically reacquire a new cookie which is why it might take a few minutes to do. Hope that clears it up for you. Glad to see you're using TGD on iOS, I suppose you're running a jailbroken device or you gave me your UDID at some point because 2.9.1 is the only available version that's out in the App Store.

Cheers!

**Comment by SunburnedGoose** [comment]
I look at all the item managers. It's good to see what works and does't
work.

I'm running iOS 8 and your version number in the app says 3.0.5. It isn't
jail broken and I haven't given you my UDID.

**Comment by SunburnedGoose** [comment]
http://imgur.com/CV3ErAd

**Comment by SunburnedGoose** [comment]
My install of TG iOS Shell had a version earlier than v2.9.1, so I have hydration enabled.  Hydration let me run the v3.0.5 code?  I do not automatically update my apps which is why I wasn't running latest.

Unfortunately, once I upgraded the iOS app to v2.9.1, it just repeatedly crash for me as soon as I opened the app.  I'll try starting the app again later.

**Comment by dasilva333** [comment]
So TGD for the Apple App Store has been 2.7.1 and 2.9.1. The first version allowed you to automatically update to the latest version via Hydration. The next release 2.9.1 has Hydra removed because it is so problematic. You probably ha 2.7.1 Hydrated to 3.0.5 which is how you got to try the latest release. I have seen problems with the app when upgrading from Hydra so if you're seeing crashes I recommend you do a full uninstall and reinstall through the App Store.
