### ISSUE TITLE
Black Spindle bug for 3.2.6

### ISSUE THREAD

**Issue by tepain** [dasilva333/TowerGhostForDestiny#403]
I obtained this weapon last night and ever since tower ghost won't load my weapons. In the bungie app this weapon shows as "Classified" light 37 , and in another app called loadouts it will show it as a blank icon and it's called "Unknown" light 37.

**Comment by slansing97** [comment]
Additional info: the Black Spindle created from a blueprint shows the same icon, light level 36.

Since I had Tower Ghost running locally I saw this debug text which I believe is the item in question.  Hope this helps:

_id: "6917529061625914185"
armorIndex: -1
artRegions: Object
bindStatus: 0
bucketName: "Equippable"
bucketType: "Primary"
canEquip: false
cannotEquipReason: 0
character: Profile
characterId: "2305843009247966831"
damageType: 0
damageTypeName: "None"
damageTypeNodeIndex: -1
damageTypeStepIndex: -1
description: "Classified"
equipRequiredLevel: 30
href: "https://destinydb.com/items/3227022822"
icon: "data/img/misc/missing_icon.png"
id: 3227022822
isEquipment: false
isEquippable: (avatarId)
isEquipped: d()
isGridComplete: false
isStoreable: (avatarId)
isUnique: false
isVisible: g()
itemDescription: "undefined"
itemHash: 3227022822
itemInstanceId: "6917529061625914185"
itemLevel: 49
location: 1
lockable: false
locked: d()
nodes: Array[0]
objectives: Array[0]
perks: Array[0]
length: 0
__proto__: Array[0]
primaryStat: d()
primaryStatValue: g()
progression: true
qualityLevel: 0
stackSize: 1
state: 0
stats: Array[0]
talentGridHash: 0
tierTypeName: "Exotic"
transferStatus: 0
typeName: "Classified"
unlockFlagHashRequiredToEquip: 2166136261
useCustomDyes: false
weaponIndex: 0

**Comment by dasilva333** [comment]
Can't be fixed, will have to wait for Bungie

**Comment by pattont** [comment]
http://www.reddit.com/r/DestinyTheGame/comments/3m8e8b/touch_of_malice_and_black_spindle_now/

It's fixed in the Bungie App now so perhaps it's available now?

**Comment by SteffanLong** [comment]
Yes, TGfD just needs a manifest update.

--
Steffan Long

**Comment by dasilva333** [comment]
It's been fixed as of 3.2.8+ thanks guys
