### ISSUE TITLE
Suggestion: Add a "Please" checkbox to the item transfer box.

### ISSUE THREAD

**Issue by DeathByNukes** [dasilva333/TowerGhostForDestiny#420]
When I dismantle an item and try to move another item into that slot, TGD refuses to do it unless I accept an item swap. It would be nice if that "feature" could at least be switched off.

Also, moving the "auto transfer stacks" checkbox into the item transfer box would make it a lot easier to use.

![image](https://cloud.githubusercontent.com/assets/1105973/10301312/d221544e-6bc6-11e5-8ced-738fe834d38c.png)

**Comment by DMWill** [comment]
oh man, i fully agree with your second idea.  that would really be great to have it right there so you could decide if you wanted to transfer the stack or not on an item by item move instead of a global option.  but your first point is not a flaw in the app, it's simply because TGD thinks you still have that item and that's why it's offering the swap out.  if you just refresh the box your working on, that item will disappear and you can move whatever you want into that spot.

**Comment by DeathByNukes** [comment]
I know it's because TGD needs a refresh. Refreshing every single time when transferring 20 engrams is painful. I want it to just take my word for it and run the item transfer API calls immediately; I want it to complain AFTER the calls actually fail rather than act like it knows more than I do.

**Comment by rkingsla** [comment]
Make no mistake - I completely agree with the issue. But, it's a common 'problem' with client-server apps. The app can only deal with the information IT has and is limited by the information that Bungie thinks it has. Yeah, there are ways around it - but each have their own negatives, and most include dramatic performance impacts, not to mention tons of data back and forth to update single items in a bucket.

I suppose, if Richard would decide to go this way, you could implement an option that would be, simply, try anyway - even if it's throws an error rather than the safer, less intrusive and user friendly(er) error free approach.

For reference, I know this particular issue well. I brought up issues much earlier this year related to refresh of local data.  There have been many discussions about the implications of such an approach. But, there is always that option of "Yeah, I get it might error....  do it anyway.  I'm a smart TGD user."

**Comment by dasilva333** [comment]
@DeathByNukes I don't agree with your first comment regarding an item swap, also auto transfer stacks has already been revamped as of 3.3.6 try it out when it's released and feel free to leave your feedback here. Thanks guys
