### ISSUE TITLE
Character headers seem to have several bugs

### ISSUE THREAD

**Issue by lightmaster** [dasilva333/TowerGhostForDestiny#439]
Can't find how to post pictures here on mobile site, so I'm linking to imgur instead: http://imgur.com/a/feGyA

First picture, notice the nice margin above the headers.

Second picture, margin is gone for first two characters, and the header for third character is missing.

Third picture, after scrolling all the way to the third character, the second character's header doesn't go off the screen but gets the nice margin back so its visible below the third character's header.

Fourth picture, after scrolling all the way past first character, its header is still visible in the empty space. The 3rd character and Vault sections need to be swapped and the next section should have already begun. (Each subsection, or weapons, armor etc aren't all lined up to save space, so why not go ahead and start the next character/Vault as soon as previous character is done?

Fifth picture, another shot showing the bottom of the app, where Vault section is on the wrong side of screen, Vault and previous character's headers overlap, and on right side, the second character (right one from very top of app) is still visible after the 3 characters header is gone.

Let me know if you need more screenshots.

**Comment by dasilva333** [comment]
First picture - working as intended, extra margin on top when first loaded all the way to the top
Second picture - 
after scrolling any amount down the margin between the top of the header and the menu is supposed to be none
header for the third character is missing - this is a new problem that resurfaced after getting fixed a long time ago, i'll investigate it and get it fixed thanks
Third picture - In this picture you're supposed to see Hunter and Titan w/o Warlock in the background I'll also get this fixed
Fourth picture - In this image you should only see the Titan emblem and no other emblem, if you scrolled past the section for the Hunter the emblem should not display anymore
Fifth picture - All I would correct in this image is the same as the 4th picture and not show the Warlock emblem and only the Vault emblem, not sure what you mean by the 'wrong side of screen' because the Vault emblem is on the left and the items for the vault are also on the left.

Thanks for all the recent feedback, good job thanks.

**Comment by lightmaster** [comment]
http://imgur.com/1I6kaW2
This is how the layout of the app currently looks on my phone. While technically it is in the right order, I think it would look much better and make more sense if the third section was always below the first section, and the fourth section always below the second section. Plus, there is a huge gap between the first section (Hunter) and the fourth section (Vault).


http://imgur.com/SPza0s4
How I think the app layout should be, regardless of whether or not one section is significantly shorter or longer than the others. Another way that's slightly different that might be better, would be to close up that gap between the Warlock and Vault in my second picture here.


Hope this makes more sense.

**Comment by dasilva333** [comment]
The app allows for two modes of display the first screen shot you presented would be with Auto Pad Height option disabled as shown here:

Auto Pad Height Disabled: http://i.imgur.com/bZmezu1.png
Auto Pad Height Enabled: http://i.imgur.com/8DrtMoh.png

After checking it out it seems to behave incorrectly at certain breakpoints like 550px so I'll be investigating it further to find a fix for when it looks like this:

http://i.imgur.com/ONPuad6.png

**Comment by lightmaster** [comment]
Auto pad height causes that massive gap after my class items. If it helps, I've got a huge amount of class items in my Vault, and it seems that it's causing the 2 characters at the top to have a huge gap to match.

**Comment by lightmaster** [comment]
Headers are fine if vault is first, but screwed up as I explained before if vault is last

**Comment by dasilva333** [comment]
@lightmaster can you provide me with some screenshots of what TGD looks like in 3.4.6 with the Vault to the right when it looks screwed up? Thanks

**Comment by lightmaster** [comment]
It's the exact same as my screenshots from before, where the first character's header in each column never disappears and shows up under the Vault and final character's headers, and also in any empty space after the first characters in each column

**Comment by dasilva333** [comment]
@lightmaster Problem with the emblem not clickable has been fixed, let me know ifyou still have any issues with 3.7.6.11+ thanks
