### ISSUE TITLE
Cannot create loadout with materials

### ISSUE THREAD

**Issue by AAraKKe** [dasilva333/TowerGhostForDestiny#50]
Every time I click on a material it shows the Plasteel icon and it doesn't matter what material I click on it assumes I am clicking the same one and remove the Plasteel from the loadout (which I didin't select, I might selected another material)

**Comment by dasilva333** [comment]
There's problems with loadouts closing this ticket in favor of issue #31 please leave any feedback there thank you

**Comment by Titus-s** [comment]
I confirm this issue. (tested on version 1.9.2 on Chrome)
First take a look at screenshot:
![screenshot_2015 04 18_10h15m00s_036_](https://cloud.githubusercontent.com/assets/11790750/7214709/16b38fcc-e5b8-11e4-94ba-ca5824fed451.png)

Scenario:
1. Click Loadouts - Create
2. Click on Heavy Ammo Synthesis -> In loadout appears Hadronic Essence (100)
3. Click on Relic Iron -> Hadronic Essence (100) disappear from loadout
4. Click on Ascendand Energy -> In loadout appears Hadronic Essence (100)
5. Click on Relic Iron -> Hadronic Essence disappear from loadout (100)
and so on...
It doesn't matter what item in materials or consumables you click or on which character. 

After that I Close loadout move Hadronic Essence (100) to another character and repeat senario.
Then in loadout start appear and disappear Spinmetal (8) 
After deeper invesitgation it turns out that in loadout always appear first item in materials on my first created character. When I moved all material from this character to another then first item in consumables start to appear in loadout.
