### ISSUE TITLE
Tower Ghost On Firefox Not Working HELP

### ISSUE THREAD

**Issue by Chase100488** [dasilva333/TowerGhostForDestiny#504]
I Am Using The Tower Ghost On My Firefox Browser And it Only Loads Up My Vault And Does Not Load Up My Guardians I Am Using Version 3.6.5.0 And Was Wanting To Know How to Fix It?

**Comment by MasterBry** [comment]
Try selecting Auto Update and Auto Refresh, that fixed the same issuse i had on my iPad, my Firefox is working as well with those two selected

**Comment by Chase100488** [comment]
I Tried That And It Still Won't Bring Up My Guardians Page Just My Vault And That's All I Wish Someone Could Tell Me If There Is A New Version

**Comment by Chase100488** [comment]
I'm Just Wanting It Fixed Because I Love Using Tower Ghost It's Easier To Move Stuff

**Comment by Chase100488** [comment]
So Can Anyone Tell Me Whats Going On?

**Comment by MasterBry** [comment]
I had the problem of not seeing my Gardians , could only see what is in my fault since Tuesdays roll out from Bungie.

Last night I installed Firefox on my iMac and got the Firefox plugin and every thing worked just fine.

This morning Ghost94 posted to select "auto update, and auto refresh" so i did that, and about 10 minutes later it was all working again on my iPad for me.

So all i can suggest is that if you have the same issue i did, delete all and reinstall and make sure and select the two auto options, and hopefully it will all come back for you as it did for my... I hope that helps

**Comment by Chase100488** [comment]
Are U Telling Me To Uninstall Firefox And Reinstall It?

**Comment by ghost74** [comment]
No dont uninsall firefox but just open the tower ghost app and just select auto update and klick on the refresh button of the app.It will download a new update and everything must be working fine then.

You dont need to uninstall firefox or the tower ghost app

**Comment by Chase100488** [comment]
yeah it's still messing up so IDK
