### ISSUE TITLE
auto update don't want to work on my android nexus 10

### ISSUE THREAD

**Issue by samfox92** [dasilva333/TowerGhostForDestiny#511]
I try to uninstall and clean  before reinstall
But each time the same the auto update don't won't to work
I ve got this message
![tmp_1752-screenshot_2015-12-10-17-06-54-910475244](https://cloud.githubusercontent.com/assets/16235047/11915639/a8fbc1de-a6af-11e5-87f0-1014f7b8474d.png)

Ty for any help

**Comment by dasilva333** [comment]
@samfox92 are you able to update to 3.7.x? If not let me know if you're sitll having problems thanks

**Comment by samfox92** [comment]
I not able to update to 3.7.x
I ve again : 
Stop the app
Clean cache
Delete data app
Uninstall the app
Reinstall from the store 
Uncheck and check the auto update check box 

And always the same .

**Comment by dasilva333** [comment]
@samfox92 I noticed I was getting manifest timeouts yesterday shortly after releasing 3.7.x perhaps it was due to the server being overloaded with requests. From the steps you provided it seems you are on the right path. Try it again today and let me know if you still have issues.

First Try:
Settings > Disable Auto Updates > Enable Auto Updates > Wait 10 mins (should reload automatically)

Second Try if it still doesn't auto update
Android > Manage Apps > Tower Ghost > Clear Cache & Clear App Data > Uninstall > Reinstall from Store > You should be on 3.6.9 with Auto Updates enabled by default > Wait 10 mins > Reloads into 3.7.0.4

Third Try
After the reinstall if it still doesn't auto update from 3.6.9 to 3.7.0 then try to disable/enable the option again to see if it unsticks.

Good luck!

**Comment by samfox92** [comment]
Hi
After I ve all you said I was always stick to the 3.6.9 version 😢
What can I do now?
Is there are a log file or information I can send to you?

**Comment by dasilva333** [comment]
@samfox92 if you tried all the above steps and it still doesn't work then I'm not sure what else to do. sorry man try it on a different phone/device (friend or family maybe) and see if you get the same results on the same connection? good luck

**Comment by samfox92** [comment]
Could you share the new version in the apk file or update Google store ?

**Comment by dasilva333** [comment]
3.7.4.1 is out in the Google Store now here's the link to the APK if you still want it: https://build.phonegap.com/apps/1426365/download/android Thanks for your help

**Comment by samfox92** [comment]
The apk install successfully but always got the error message for auto update.
For me it s good like this if I can get the apk at each realise.
Ty
