### ISSUE TITLE
Icons not loading, showing broken image

### ISSUE THREAD

**Issue by burns11** [dasilva333/TowerGhostForDestiny#525]
![screenshot_2015-12-24-00-09-48](https://cloud.githubusercontent.com/assets/15721993/11989855/17e6b470-a9d3-11e5-9fa1-14232e6dc911.png)

I have cleared data and cache, didn't fix it.  Ver 3.7.4.1

Android by the way

**Comment by killi2** [comment]
same on chrome

**Comment by LtHitlis** [comment]
Same with my iPad. 
![image](https://cloud.githubusercontent.com/assets/14055765/11990352/ec1517a2-a9d1-11e5-99ec-41dd40e21503.png)

**Comment by SecondCarpet** [comment]
Reinstall the app. Worked for me

**Comment by nessus42** [comment]
I see this same problem with the 3.7.4.1 Mac application. Reinstalling didn't fix the problem.

Additional issues I've noticed with this release:

(1) In Firefox, clicking on the left of the emblem doesn't cause that character to reload. (This feature still works in the Mac app, even though all the icons are broken.)

(2) In Firefox, if you go into full-screen mode, it doesn't use the scaling-down CSS that causes the tooltips to fit on the screen.

(3) In Firefox, when not in full-screen mode, the scaling-down CSS ***is*** used, but the tooltips are often placed too high on the screen so that the top of the tooltip (which includes the item's name) is clipped.

**Comment by dasilva333** [comment]
Sorry about that guys, it was a combination of testing my changes only on a few devices and me not realizing the older bootstrap file isn't compatible with the new code, I made a fix this morning as of 3.7.4.2 to make sure that type of problem never occurs again. Let me know if anyone still has problems. Thanks for the quick heads up.

@nessus42 regarding issue 1 thats already another ticket
regarding issue 2 it bases the scaling based on the current witdth of your view port at the time of it becoming visible
regarding issue 3 I'd like to see a screenshot of that if you could try capturing one and post it under issue #487 thanks

**Comment by mistral13** [comment]
@nessus42
Regarding issus 3 I'd like also to know the resolution from your screen.
