### ISSUE TITLE
Tier 12 / Custom -> different T12 solutions

### ISSUE THREAD

**Issue by mistral13** [dasilva333/TowerGhostForDestiny#610]
Hi
If i us the function T12 Build on my Titan it result only a 2/5/5 solution.
If i us the function Custom with the current armore it result a 5/5/2 solution.
3.9.0.5 Version

Why it does not display the 5/5/2 solution with the T12 Build function?

https://towerghostfordestiny.com/share/?psn/mistral75

**Comment by dasilva333** [comment]
> If i us the function T12 Build on my Titan it result only a 2/5/5 solution.

That means the 2/5/5 solution provides the most points over any other solution.

> If i use the function Custom with the current armor it result a 5/5/2 solution.

That's because you equipped a 5/5/2 solution and then clicked on Equipped?

> Why it does not display the 5/5/2 solution with the T12 Build function?

It defaults to the 2/5/5 solution, the T12 Build function is an explorer not a report style tool, so you'll be presented with the best set and from there you're free to change the selection to find what other possibilities there are. Basically it's working as intended. 

Let me know if that clears it up for you. Thanks!

**Comment by mistral13** [comment]
With the T12 Function, its show more then 1 solution only all solutions have the same points. Is this correct?

T12 Function should provide the most poinst.
T12 Build 12.727 Points. 


![image](https://cloud.githubusercontent.com/assets/5049663/15291598/0bdfbe60-1b7f-11e6-9bd7-c295907680e5.jpeg)

Custom 12.728 Point for the equipped Armor

![image](https://cloud.githubusercontent.com/assets/5049663/15291599/0c036478-1b7f-11e6-9bab-413404c50d99.jpeg)

Have both function the same math functions?
Working as intended?

**Comment by dasilva333** [comment]
Yes working as intended, the key difference in Custom and T12 Build is that Custom will allow combination to show up (in your case it happens to be a 5/5/2 build) and in T12 Build it will only pick those sets that can reach T12.

So here's the whole process:

-find the armor with the most points,
-calculate the best sets
-pick the first one in Custom (in your case it happens to be 5/5/2)
-filter for all T12 combos in T12 Build (in your case 2/5/5 happens to sort towards the top)
-equip found set as the default selected set

Hope that makes sense, good luck!
