### ISSUE TITLE
[request] icons at top of screen to jump to characters

### ISSUE THREAD

**Issue by DrPippin** [dasilva333/TowerGhostForDestiny#65]
Request for having shortcut icons at top of screen (between version number and settings icon) to jump to the different characters. I envision using the same icons as when selecting which character to transfer something to. Reason for the request is that scrolling through a long list of weapons/armor/consumables/etc to get to the second or third character takes quite a while, and being able to jump immediately to that character would be much faster. Plus, with so many things in the list, I sometimes get lost when scrolling rapidly as to which character's inventory is currently on the screen.

**Comment by dasilva333** [comment]
Not sure man there's a lot of ideas on how to improve usability and filtering I'll leave this one pinned and decide later which one to go with so far we got:

1. Collapsible Emblems
2. Swipe Left/Right for each character
3. Shortcut icons
4. menu based filters

Thanks for your feedback

**Comment by DrPippin** [comment]
Those are all good ideas. Never thought about swiping between characters - I think I like that one the most. Better to have too many ideas than not enough! I appreciate the work you're doing on this app.

**Comment by yunaforever009** [comment]
Dasilva333, here's an idea that might work by combining some of your ideas with a visual cue of how it functions on mobile devices:

Between the label/version number and the settings button is a wide space that currently serves as only a divider. What if you placed the Vault and Emblems for each character in the space, organized by character slot? Each emblem for Vault, Char 1, Char 2, and Char 3 would be selectable and when selected would move your screen to that character's inventory screen. It would then highlight the associated emblem so that you have a quick heads up view of which inventory you are viewing. This would require the settings bar to remain visible while browsing but I think that the added benefit of quick character switching would outweigh the vertical viewing space. 

You could also implement the swipe left/right feature and it would then highlight the emblem at the top in the settings bar to show which character you are swiping to and allow a quick return to the vault, for example. 

*I'm running TGD on a Galaxy S4 primarily in Portrait mode, just as a note on how my view appears. Attaching a quick mock-up to show how it might look.
![test layout of char select](https://cloud.githubusercontent.com/assets/2084381/7231182/e0022c14-e741-11e4-8b01-8141b948d968.png)

**Comment by dasilva333** [comment]
@yunaforever009 I think that's a great mockup of what @DrPippin suggested. I also believe that this idea could still work with idea #1 and #2 and #4 so it seems likely that I'll implement this one sooner rather than later since it won't conflict with future ideas.

Thanks for the great feedback guys

**Comment by yunaforever009** [comment]
@dasilva333 , thanks for the great work you've given us all!

**Comment by yunaforever009** [comment]
@dasilva333 Nice work on that addition. I'm absolutely loving the quick scroll feature. As a follow-up question, what about incorporating a small number on the vault icon that displays the remaining number of empty spaces in the vault?

**Comment by dasilva333** [comment]
@yunaforever009 sorry I don't agree with that design feature, however I do like how the quick scroll turned out, i'll try to make it better in the future by adding a border to the ones you have active. i'm also going to leave a note in this ticket that holding the icon shows a popup with the unique name of the character.
thanks guys

**Comment by DrPippin** [comment]
Your implementation of the quick scroll was exactly how I had envisioned it, and I love it as a new addition to the app.  Very nicely done.  Long hold on the icons giving the unique character name is a nice plus, too!
