### ISSUE TITLE
[bug] Version 3.9.3.2 Loadout menu is empty

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#677]
Only items in the menu are Manage, Create, Cancel. No loadouts appear here.

Chrome and iOS.

Have logged out and back in on both platforms and toggled auto-update off and back on.

**Comment by edmiller47** [comment]
If it helps, I'm getting a "loading manifest timeout" error when starting TG on Chrome.

**Comment by edmiller47** [comment]
Now working correctly on both platforms. Thanks once again.

**Comment by edmiller47** [comment]
... aaand it's broken again

**Comment by edmiller47** [comment]
![image](https://cloud.githubusercontent.com/assets/13838005/20264024/7aa42934-aa37-11e6-8acb-a8e7d65e96e3.png)

**Comment by edmiller47** [comment]
Just rebooted router. After a couple of attempts, TG started up, gave me the error shown above, but loadout menu items are present.  Any idea what's going on?

**Comment by Grimsalt** [comment]
I've had this version on a few days, no issues.  Until.  The app asked to renew sign-in credentials.  Since then, it's been stuck in a "Checking for updates / Downloading updates" loop.  The download bar stops half way, even after Uninstall/Reinstall.  Probably same bug reported here : 

https://www.reddit.com/r/TowerGhostForDestiny/comments/5ck52b/multiple_issues_this_morning_auto_update_manifest/

**Comment by dasilva333** [comment]
@edmiller47 so loadouts are now working and loading for you? 

@Grimsalt have you tried a full reinstall and clearing your app cache in android? feel free to follow issue #670 for more info on that

**Comment by edmiller47** [comment]
Yes, loadouts are fine and I'm not getting that error message any longer.
