### ISSUE TITLE
[Suggestion] Remove empty rows

### ISSUE THREAD

**Issue by fremgenc** [dasilva333/TowerGhostForDestiny#88]
Android user here, but I think this will apply to all mobile versions.

There are currently 9 open spots per weapon/armor type per character. 3 rows by 3 columns.

Some of my characters only have 1 or two guns, which take up 1 row. The other two rows are left empty. This is the case for several weapon and armor types.

My suggestion is to remove the empty rows when they're not in use, to allow for quicker and cleaner scrolling.
![screenshot_2015-04-23-17-05-24](https://cloud.githubusercontent.com/assets/12090308/7307483/364e61f0-e9db-11e4-8cb5-3d858f21e3ff.png)

**Comment by dasilva333** [comment]
I'll make it an option

**Comment by pattont** [comment]
Yea, because another post wanted everything lined up. I guess it's a preference. I would rather have it lined up so it is easier to just look horizontal at the things each char has.

**Comment by wickles** [comment]
@dasilva333 nice change but it doesn't revert back to being unpadded when the option is turned on then off.

**Comment by lanejcf** [comment]
Excellent idea of making it an option, but I would like to make a suggestion, possibly for when there is  width to show all 3 guardians side by side, as when using a laptop and chrome.

Ensure that when excess padding is removed, the sections remain in alignment across all three guardians as in image below

![proposed_with_padding](https://cloud.githubusercontent.com/assets/11978393/7332830/a683ca10-eb4c-11e4-9d6c-bf2098b5e600.jpg)

As you can see from the image above I propose that as many full blank rows that exist in all 3 guardians are removed.
e.g.
3 rows are required for all Primary blocks since guardian 1 has 7 items in store (3 rows) 
2 rows are only required for all Secondary since no guardian has a requirement for a 3rd row
1 row is required for all Heavy on all guardians
2 rows are required for all Helmets since Guardian 1 requires 2 rows even though guardians 2 and 3 do not need it

This method would mean that true horizontal alignment is maintained when the screen width is available at the same time as minimising the vertical scrolling required, an HMI update making the data clearer and easier to use.

Thanks for the time you spend on this program, that is becoming a integral part to playing Destiny  -now where is that donate button :)

Jonathan

**Comment by dasilva333** [comment]
@lanejcf hey sorry I didn't reply your comment is very insightful and thought out, it's a good idea and I'll be working on that in the long term. Thanks for your feedback

**Comment by dasilva333** [comment]
@lanejcf the newest version of auto pad height 2.7.3 will work the way you described thanks for your feedback ill be closing this issue now
